name: Laravel CI/CD on Koyeb

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install PHP and Dependencies
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo_mysql
        tools: composer

    - name: Install Laravel Dependencies
      run: composer install --no-dev --prefer-dist --optimize-autoloader

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Up .env File
      run: |
        echo "APP_NAME=Laravel" > .env
        echo "APP_ENV=production" >> .env
        echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
        echo "APP_DEBUG=false" >> .env
        echo "APP_URL=${{ secrets.APP_URL }}" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Install Koyeb CLI
      run: curl -fsSL https://get.koyeb.com | bash

    - name: Deploy to Koyeb
      env:
        KOYEB_API_KEY: ${{ secrets.KOYEB_API_KEY }}
      run: koyeb service deploy --name laravel-app --git $GITHUB_REPOSITORY --branch main --env-file .env
