name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Authenticate Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: echo "Using Railway Token"

    - name: Ensure Database Exists in Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway service list | grep "mysql" || railway service new --name laravel-db --template mysql

    - name: Fetch Database Credentials
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway variables > railway_env.txt

    - name: Configure Laravel Environment
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=$(grep 'MYSQLHOST' railway_env.txt | cut -d'=' -f2)" >> .env
        echo "DB_PORT=$(grep 'MYSQLPORT' railway_env.txt | cut -d'=' -f2)" >> .env
        echo "DB_DATABASE=$(grep 'MYSQLDATABASE' railway_env.txt | cut -d'=' -f2)" >> .env
        echo "DB_USERNAME=$(grep 'MYSQLUSER' railway_env.txt | cut -d'=' -f2)" >> .env
        echo "DB_PASSWORD=$(grep 'MYSQLPASSWORD' railway_env.txt | cut -d'=' -f2)" >> .env

    - name: Install PHP and Dependencies
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo_mysql
        tools: composer

    - name: Install Laravel Dependencies
      run: composer install --no-dev --prefer-dist --optimize-autoloader

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway deploy
